### ISSUE TITLE
Update documentation to recommend which plugin to use

### ISSUE THREAD

**Issue by MikeTheSnowman** [lobodpav/spock-intellij-plugin#3]
**Is your feature request related to a problem? Please describe**:
There is not technical problem, but more of a marketing problem.
If you go to the IntelliJ Marketplace to look for "spock framework" support, there are two potential options. The most popular option is called `Spock Framework Enhancements` (which hasn't been updated in 4 years) and the other option is your plugin `Spock Framework Support`.
People, like me, will get a little confused on which one that we should download.
Maybe there's some difference in features, or maybe you have some things planned (roadmap) what you want for users to consider.

**Describe the solution you'd like**:
I think your readme, or the plugin description in the IntelliJ Marketplace should be updated for users (like me) who might get a little confused on which spock plugin they should consider to download and install.

**Describe alternatives you've considered**:
N/A

**Additional context**:
N/A

**Comment by lobodpav** [comment]
Hey there, @wtfacoconut. You've got a good point. I will improve the doc in the next release. Thanks for the hint!

**Comment by lobodpav** [comment]
Fixed in [v1.0.1](https://github.com/lobodpav/spock-intellij-plugin/releases/tag/v1.0.1).
